title: Salado Youth Football
description: Official site for Salado Youth Football and Cheer
baseurl: ""
url: "https://salado-youth-football.netlify.app"
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
  - jekyll-seo-tag
