title: Salado Youth Football
email: info@saladofootball.com
description: >-
  Official site for Salado Youth Football & Cheer.
baseurl: ""
url: "https://salado-youth-football.netlify.app"
theme: minima
plugins:
  - jekyll-feed
